### PR TITLE
TFMini driver, DistanceSensor interface, uart fixes

### LINKED ISSUE #555: Time of flight Proximity: TFMini
https://www.sparkfun.com/products/14588

### LINKED ISSUE #603: Fix and verify that all L1 utility methods are marked const.

### PR DESCRIPTION
**Pull request by ZackeryPlovanic**
* Created a pure virtual interface for distance sensors to abide by.
* Developed device driver for the Time of Flight proximity sensor, TFMini
* Added the const keyword to the uart.hpp utility functions

Resolves #555
Resolves #603

### CODE REVIEW

File: library/L2_HAL/sensors/distance/timeofflight/tfmini.hpp [hunk 1]
```diff
@@ -0,0 +1,224 @@
...
+  const Uart & uart_pin_;
+  uint8_t min_threshold_ = 20;
+
+  bool SendCommandAndCheckEcho(const uint8_t * command) const
+  {
+    bool success = true;
+    uint8_t echo[kCommandLength];
+
+    uart_pin_.Write(command, kCommandLength);
+    uart_pin_.Read(echo, kCommandLength, 1000);
```
Comment (kammce) [inline library/L2_HAL/sensors/distance/timeofflight/tfmini.hpp]:
```suggestion
    uart_pin_.Read(echo, kCommandLength, kTimeout);
```

Do this across all files. If you are using the same timeout value everywhere, it should be a variable name.

File: library/L2_HAL/sensors/distance/timeofflight/tfmini.hpp [hunk 2]
```diff
@@ -0,0 +1,227 @@
...
+  {
+    bool success = true;
+    uint8_t echo[kCommandLength];
+
+    uart_pin_.Write(command, kCommandLength);
+    uart_pin_.Read(echo, kCommandLength, kTimeout);
+    for (int i = 0; i < kCommandLength; i++)
+    {
+      if ((kEchoSuccess[i] != echo[i]) && (kConfigExit[i] != echo[i]))
+        success = false;
```
Comment (kammce) [inline library/L2_HAL/sensors/distance/timeofflight/tfmini.hpp]: should break at this point.

Comment (kammce) [inline library/L2_HAL/sensors/distance/timeofflight/tfmini.hpp]: Use curly braces for all conditional blocks. Singular blocks are not acceptable in SJSU-Dev2.

File: library/L2_HAL/sensors/distance/timeofflight/tfmini.hpp [hunk 3]
```diff
@@ -0,0 +1,230 @@
...
+  /// @returns Status::kBusError if initialization fails
+  /// @returns Status::kSuccess if initialization succeeds
+  Status Initialize() const override
+  {
+    Status init_success;
+    init_success = uart_pin_.Initialize(kBaudRate);
+    if (init_success == sjsu::Status::kSuccess)
+    {
+      bool device_init = true;
+      if (!SendCommandAndCheckEcho(kConfigCommand))
```
Comment (kammce) [inline library/L2_HAL/sensors/distance/timeofflight/tfmini.hpp]: Curly braces needed here.

File: library/L2_HAL/sensors/distance/timeofflight/tfmini.hpp [hunk 4]
```diff
@@ -0,0 +1,230 @@
...
+    {
+      low_limit = kStrengthLowerLimitCap;
+    }
+    for (int i = 0; i < kCommandLength; i++)
+    {
+      updated_min_threshold_command[i] = kUpdateMinThresholdCommand[i];
+    }
+    updated_min_threshold_command[kThresholdByte] = low_limit;
+    if (!SendCommandAndCheckEcho(kConfigCommand))
+      device_updated = sjsu::Status::kBusError;
```
Comment (kammce) [inline library/L2_HAL/sensors/distance/timeofflight/tfmini.hpp]: Curly braces need here
